### ISSUE TITLE
Weapon Item Hover

### ISSUE THREAD

**Issue by Caliwhi7** [ApourtArtt/NostaleWidget#21]
Adding new rarity string + define the color

**Comment by ApourtArtt** [comment]
For the color it is now possible with the latest commit
![image](https://user-images.githubusercontent.com/47370292/173227778-c4d9e298-591d-4209-aac4-e4d78a636846.png)


Text still needed, but I think it will take some time (I will lack of it for the following week)

**Comment by ApourtArtt** [comment]
To give some news, being able to add text for the rarity is not as easy as it can be, the client is manually appending those ID:
```cpp
277Damaged
278Low-level
279
280Useful:
281Good:
282High quality:
283Excellent:
284Ancient:
285Mysterious:
286Legendary:
4224Phenomenal:
```

as can be seen here:
![image](https://user-images.githubusercontent.com/47370292/173791241-0727f5bc-c2ff-4773-8807-49a7f7f43f96.png)

Manually adding one rarity works, but creates a lot of issues (in short: every strings after 286 behave as id+1 : "Neutral" (287) becomes "Divines" (288), etc.

It requires to:
- hook somewhere in order to have a copy of Constring (which gets deleted after the splashscreen gets hidden)
- hook the "append rarity before item name" function
- change the whole initialization system in order to be able to get Constring before deletion

Still in work and should be ready for this week-end.

**Comment by ApourtArtt** [comment]
To give some news²:
![image](https://user-images.githubusercontent.com/47370292/174388180-155a5124-5b56-451b-af4a-8ce1c3c5dd65.png)
As you can see the character sheet is not done yet though. I haven't started this part, I plan on having finished for this week-end (no promises though, as I said, not started, even researches)

**Comment by ApourtArtt** [comment]
To give some news^3, everything is now working as expected
![image](https://user-images.githubusercontent.com/47370292/174446752-7f2c1b07-f121-4e74-9c00-877d2b701a5e.png)
