### ISSUE TITLE
discord refresh

### ISSUE THREAD

**Issue by Lyzard-NS** [ApourtArtt/NostaleWidget#25]
when replaced EWSF it works but discord stays on logging in

**Comment by Price-H16** [comment]
Yes same here

**Comment by ApourtArtt** [comment]
Hello, it is not a problem from your side, Discord system is implemented but I need to make some researchs before continuing it, for example, I currently have no clue how to consider a character fishing, etc and I don't want any modification on the server in order to control the Discord status.

As a temporary alternative, you can change Discord status by using the `DiscordManager::SetActivity` function and complete [this](https://github.com/ApourtArtt/NostaleWidget/blob/main/ClientModding/Api/Managers/DiscordManager/DiscordManager.cpp#L55) function.

I plan on completing the Discord Manager after this issue: https://github.com/ApourtArtt/NostaleWidget/issues/22

**Comment by Price-H16** [comment]
Okay but it should change name and channel or no ?

**Comment by ApourtArtt** [comment]
Indeed, are you sending the tit packet? If yes, can you please add [here](https://github.com/ApourtArtt/NostaleWidget/blob/main/ClientModding/ClientModding.cpp#L115) this:
```cpp
Logger::Log("Pseudonym: \"%s\" Channel: %d", pseudo.c_str(), connectionMng.GetServChanManager().GetChannel());
```
and give me the result?

**Comment by Price-H16** [comment]
Nothing it didn't do anything

**Comment by Price-H16** [comment]
So problem is in tit packet ?

**Comment by Lyzard-NS** [comment]
i got at least tit packet but still logging in

**Comment by Lyzard-NS** [comment]
And in logger shows name and channel but discord.... I think need complete

**Comment by ApourtArtt** [comment]
> Nothing it didn't do anything

I think your server is not sending `tit` packet, please check on this side with a packetlogger (you will need to replace the custom EWSF.EWS by the original one in order to inject a packetlogger)



> i got at least tit packet but still logging in

As a second step can you please add [here](https://github.com/ApourtArtt/NostaleWidget/blob/main/ClientModding/Api/Managers/DiscordManager/DiscordManager.cpp#L56)
something like:
```cpp
Logger::Log("Pseudonym: %d, Channel: %d", pseudonym.empty(), channel)
```

Also can you please tell me when you cloned for the last time ?

If you want the flow:
1) tit is subscribed [here](https://github.com/ApourtArtt/NostaleWidget/blob/main/ClientModding/ClientModding.cpp#L19)
2) tit is handled [here](https://github.com/ApourtArtt/NostaleWidget/blob/main/ClientModding/ClientModding.cpp#L111)
3) discord status is refreshed [here](https://github.com/ApourtArtt/NostaleWidget/blob/main/ClientModding/ClientModding.cpp#L102) (called every [EventLoopDelay](https://github.com/ApourtArtt/NostaleWidget/blob/main/ClientModding/main.cpp#L138) milliseconds)

**Comment by Price-H16** [comment]
Now I got same problem nothing changed still logging in even when it knows name and channel and tit packet sended 

Latest version of repo

**Comment by ApourtArtt** [comment]
Does the log line described in the comment above yours appear?

**Comment by Price-H16** [comment]
Yes

**Comment by ApourtArtt** [comment]
I changed the way Discord module is supposed to be used, multiple persons tried and it seems to work correctly now. Please don't forget to add discord_game_sdk.dll if you want to give it another try.
